import type { Metadata } from 'next'

import { pretendard } from '@package/ui/fonts/pretendard'
import { BaseLayout } from '@package/ui/layouts/base-layout'
import { PrefetchCrossZoneLinks } from '@package/ui/scripts/prefetch-cross-zone-links'

import '#styles/globals.css'

export const metadata: Metadata = {
  title: 'Blog | Wontory',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" className={pretendard.variable}>
      <body>
        <BaseLayout path="/blog">{children}</BaseLayout>
        <PrefetchCrossZoneLinks hrefs={['/', '/craft']} />
      </body>
    </html>
  )
}
